title: Matthew Lang
description: My web development notes
theme: jekyll-theme-cayman
permalink: /:title:output_ext

collections_dir: articles
collections:
  ruby_on_rails:
    output: true
    permalink: /:collection/:name